# Generated by Django 5.2.6 on 2025-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
    ]
